### ISSUE TITLE
Ensure the state of features (permissions) in namespaces using a controller

### ISSUE THREAD

**Issue by sandromello** [kolihub/koli#57]
Breaking issue #54

The controller must watch for namespaces and associate a service plan. Ensure features are properly set based on the information of a plan.

### Example of a ServicePlan

```
apiVersion: sys.koli.io/v1alpha1
kind: Serviceplan
metadata:
  name: standard
  labels:
    'koli.io/clusterplan': 'professional'
spec:
  # The broker could create a service plan limiting the amount of object resources 
  # Any of Object Count Quota: http://kubernetes.io/docs/admin/resourcequota/
  hard:
    pods: 10
    services: 15
    configmaps: 25
  # Rbac policies are used to restrict access to specific resources management
  features:
    podManagement:
      exec: false
      attach: false
      portForward: true
      scale: false
      autoscale: false
    addonManagement: true
    metricsAccess: false
```
