### ISSUE TITLE
koli-system namespace must access all services from the cluster

### ISSUE THREAD

**Issue by cainelli** [kolihub/koli#95]
Once kong upstreams are usually services kong pods must reach services on every ns. Since calico prevent access between namespaces by default we need to discuss a way to allow that, kong-system -> N namespaces.

**Comment by cainelli** [comment]
One solution may be attach a network policy on each namespace with privileges to pods within `koli-system` namespace. We would have to attach a label on `koli-system` namespace, in the following example `kolihub.io/system: true`

```yaml 
kind: NetworkPolicy
apiVersion: extensions/v1beta1
metadata:
  name: koli-system
spec:
  podSelector:
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            kolihub.io/system: 'true'
```
